/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMainRouteImport } from './routes/_authenticated/main'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedTaskCreateRouteImport } from './routes/_authenticated/task/create'
import { Route as AuthenticatedTaskCodeRouteImport } from './routes/_authenticated/task/$code'
import { Route as AuthenticatedProjectProjectIdSprintRouteImport } from './routes/_authenticated/project/$projectId/sprint'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMainRoute = AuthenticatedMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTaskCreateRoute = AuthenticatedTaskCreateRouteImport.update({
  id: '/task/create',
  path: '/task/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTaskCodeRoute = AuthenticatedTaskCodeRouteImport.update({
  id: '/task/$code',
  path: '/task/$code',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectProjectIdSprintRoute =
  AuthenticatedProjectProjectIdSprintRouteImport.update({
    id: '/project/$projectId/sprint',
    path: '/project/$projectId/sprint',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/main': typeof AuthenticatedMainRoute
  '/task/$code': typeof AuthenticatedTaskCodeRoute
  '/task/create': typeof AuthenticatedTaskCreateRoute
  '/project/$projectId/sprint': typeof AuthenticatedProjectProjectIdSprintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/main': typeof AuthenticatedMainRoute
  '/task/$code': typeof AuthenticatedTaskCodeRoute
  '/task/create': typeof AuthenticatedTaskCreateRoute
  '/project/$projectId/sprint': typeof AuthenticatedProjectProjectIdSprintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authenticated/main': typeof AuthenticatedMainRoute
  '/_authenticated/task/$code': typeof AuthenticatedTaskCodeRoute
  '/_authenticated/task/create': typeof AuthenticatedTaskCreateRoute
  '/_authenticated/project/$projectId/sprint': typeof AuthenticatedProjectProjectIdSprintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/main'
    | '/task/$code'
    | '/task/create'
    | '/project/$projectId/sprint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/main'
    | '/task/$code'
    | '/task/create'
    | '/project/$projectId/sprint'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/main'
    | '/_authenticated/task/$code'
    | '/_authenticated/task/create'
    | '/_authenticated/project/$projectId/sprint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/main': {
      id: '/_authenticated/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthenticatedMainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/task/create': {
      id: '/_authenticated/task/create'
      path: '/task/create'
      fullPath: '/task/create'
      preLoaderRoute: typeof AuthenticatedTaskCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/task/$code': {
      id: '/_authenticated/task/$code'
      path: '/task/$code'
      fullPath: '/task/$code'
      preLoaderRoute: typeof AuthenticatedTaskCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectId/sprint': {
      id: '/_authenticated/project/$projectId/sprint'
      path: '/project/$projectId/sprint'
      fullPath: '/project/$projectId/sprint'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdSprintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMainRoute: typeof AuthenticatedMainRoute
  AuthenticatedTaskCodeRoute: typeof AuthenticatedTaskCodeRoute
  AuthenticatedTaskCreateRoute: typeof AuthenticatedTaskCreateRoute
  AuthenticatedProjectProjectIdSprintRoute: typeof AuthenticatedProjectProjectIdSprintRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMainRoute: AuthenticatedMainRoute,
  AuthenticatedTaskCodeRoute: AuthenticatedTaskCodeRoute,
  AuthenticatedTaskCreateRoute: AuthenticatedTaskCreateRoute,
  AuthenticatedProjectProjectIdSprintRoute:
    AuthenticatedProjectProjectIdSprintRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
